Section A: Data Structures & Control Structures

1.Create a list of 5 integers

In [9]:
lst = [2,3,4,5,6]
lst

[2, 3, 4, 5, 6]

In [2]:
lst.append(90)
lst

[2, 3, 4, 5, 6, 90]

In [3]:
lst.extend([70,80])
lst

[2, 3, 4, 5, 6, 90, 70, 80]

In [4]:
lst.insert(1,444)
lst

[2, 444, 3, 4, 5, 6, 90, 70, 80]

In [5]:
lst.remove(2)
lst

[444, 3, 4, 5, 6, 90, 70, 80]

In [6]:
lst.pop()
lst

[444, 3, 4, 5, 6, 90, 70]

In [7]:
lst.clear()
lst

[]

In [10]:
lst.index(3)

1

In [11]:
lst.count(5)

1

In [16]:
lst.sort()
lst

[2, 3, 4, 5, 6]

In [13]:
print(lst.sort())

None


In [14]:
#add
lst.sort(reverse=True)
lst

[6, 5, 4, 3, 2]

In [17]:
# without order
lst.reverse()
lst

[6, 5, 4, 3, 2]

2.	Create a tuple that stores 3 student names. 

In [18]:
t = ('Arun','Bharath','Suresh')
t

('Arun', 'Bharath', 'Suresh')

In [19]:
t.index('Bharath')

1

In [20]:
t.replace('Bharath','Manu')

AttributeError: 'tuple' object has no attribute 'replace'

In [21]:
t.change('Bharath','Manu')

AttributeError: 'tuple' object has no attribute 'change'

Only 2 operations count & index can be done.
Can't  directly change (mutable) the elements of a tuple bcs tuple are immutable data type of python.
Attempt to do so result in error as shown above.

3.	Create a set of integers with some duplicate values

In [22]:
set = {111,333,666,888,222,333,666}
print(set)

{888, 666, 333, 222, 111}


Set is an unorderedcollection of items where every element is unique.
If u try to create a set with duplicate values,python will automaticallyremove the duplicates.
Even we created set of integers with duplicates of 333 & 666,the output only shows them 
only once because set donot allow duplicate elements,they only store unique values
 The order may vary as sets are unordered.

4.	Create a dictionary 

In [23]:
d = {'Name':'Arun',
     'Age':26,
     'City':'Trichy'}
d

{'Name': 'Arun', 'Age': 26, 'City': 'Trichy'}

In [24]:
d['Age']=30
d

{'Name': 'Arun', 'Age': 30, 'City': 'Trichy'}

In [25]:
d2 = {'Name':'Bharath',
     'Age':28,
     'City':'Bangalore',
     'email':'xyz@gmail.com'}
d2

{'Name': 'Bharath', 'Age': 28, 'City': 'Bangalore', 'email': 'xyz@gmail.com'}

In [26]:
d2.update(d)
d2

{'Name': 'Arun', 'Age': 30, 'City': 'Trichy', 'email': 'xyz@gmail.com'}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). 

In [27]:
Age= int(input('Enter your age:'))
    

Enter your age: 20


In [28]:
if Age>=18:
    print('ur eligible to vote')
    print('any person whose age is above is 18 can vote in elections')
else:
    print('ur not eligoble to vote')
    print('come after u attain age 18')

ur eligible to vote
any person whose age is above is 18 can vote in elections


6.	Given a 'marks' variable.

In [29]:
mark = 95
if mark >=90:
    grade='A'
elif mark >=75 and mark<=89:
     grade='B'
elif mark >=50  and mark<=74:
     grade ='C'
elif mark < 50:
     grade = 'fail'
else:
     grade ='Try again'
print(grade)
   

A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [30]:
num = int(input("Enter a number:"))

Enter a number: -8


In [31]:
if num > 0:
   if num % 2 == 0:
        print('num is positive & even')
elif num == 0:
        print('num is equal to zero')
else:
        print('num is negative')

num is negative


Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [32]:
import numpy as np

In [33]:
scalar = np.array(5)
print(scalar)

5


In [34]:
array_1d = np.arange(1,6)
print(array_1d)

[1 2 3 4 5]


In [35]:
array_2d = np.arange(10,70,10).reshape(2,3)
print(array_2d)

[[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [36]:
random_array = np.random.randint(0,101,size=(4,4))
print(random_array)

[[31 94 98 24]
 [96 89 13 60]
 [28 14 75  9]
 [17 82 70 89]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [37]:
import pandas as pd

In [38]:
arr_3x3 = np.random.rand(3,3)
df = pd.DataFrame(arr_3x3,columns=['A','B','C'])
print(df)

          A         B         C
0  0.090123  0.657664  0.470969
1  0.635115  0.840936  0.211472
2  0.967072  0.572573  0.417649


Section C: Exploring Pandas

11.	Create a small DataFrame 

In [39]:
import pandas as pd
import numpy as np

In [40]:
edata=[
    ['Arun',26,'Trichy',200],
    ['Bharath',28,'Bangalore',500],
    ['Chetan',30,'Mangalore',300],
    ['Danu',28,'Delhi'],
    ['Gani',23,'Indore',400],
    ['Hari',23,'Jaipur',100],
    ['Jay',24,'Varanasi',400],
    ['Hari',23,'Jaipur',100],
    ['Suresh',30,'Hyderabad',800],
    ['Vamshi',25,'Kurnool',240]
    
]

In [41]:
e1 = pd.DataFrame(edata)
e1

,0,1,2,3
0,Arun,26,Trichy,200.0
1,Bharath,28,Bangalore,500.0
2,Chetan,30,Mangalore,300.0
3,Danu,28,Delhi,NaN
4,Gani,23,Indore,400.0
5,Hari,23,Jaipur,100.0
6,Jay,24,Varanasi,400.0
7,Hari,23,Jaipur,100.0
8,Suresh,30,Hyderabad,800.0
9,Vamshi,25,Kurnool,240.0


In [42]:
e2=pd.DataFrame(edata,columns=['NAME','AGE','CITY','SALARY'],index=[1,2,3,4,5,6,7,8,9,10])
e2   

,NAME,AGE,CITY,SALARY
1,Arun,26,Trichy,200.0
2,Bharath,28,Bangalore,500.0
3,Chetan,30,Mangalore,300.0
4,Danu,28,Delhi,NaN
5,Gani,23,Indore,400.0
6,Hari,23,Jaipur,100.0
7,Jay,24,Varanasi,400.0
8,Hari,23,Jaipur,100.0
9,Suresh,30,Hyderabad,800.0
10,Vamshi,25,Kurnool,240.0


In [43]:
#A-- Use .info(), .describe()
e2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   NAME    10 non-null     object 
 1   AGE     10 non-null     int64  
 2   CITY    10 non-null     object 
 3   SALARY  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [44]:
e2.describe()

,AGE,SALARY
count,10.000000,9.000000
mean,26.000000,337.777778
std,2.828427,221.007793
min,23.000000,100.000000
25%,23.250000,200.000000
50%,25.500000,300.000000
75%,28.000000,400.000000
max,30.000000,800.000000


In [45]:
#B-Select 'Name' and 'City' columns
e2[['NAME','CITY']]

,NAME,CITY
1,Arun,Trichy
2,Bharath,Bangalore
3,Chetan,Mangalore
4,Danu,Delhi
5,Gani,Indore
6,Hari,Jaipur
7,Jay,Varanasi
8,Hari,Jaipur
9,Suresh,Hyderabad
10,Vamshi,Kurnool


In [46]:
#C-Drop 'City' column
e2.drop('CITY',axis=1)

,NAME,AGE,SALARY
1,Arun,26,200.0
2,Bharath,28,500.0
3,Chetan,30,300.0
4,Danu,28,NaN
5,Gani,23,400.0
6,Hari,23,100.0
7,Jay,24,400.0
8,Hari,23,100.0
9,Suresh,30,800.0
10,Vamshi,25,240.0


In [47]:
#D-- Fill any missing values in 'Salary' column with the mean
e2.isna()

,NAME,AGE,CITY,SALARY
1,False,False,False,False
2,False,False,False,False
3,False,False,False,False
4,False,False,False,True
5,False,False,False,False
6,False,False,False,False
7,False,False,False,False
8,False,False,False,False
9,False,False,False,False
10,False,False,False,False


In [48]:
avg_SALARY=e2['SALARY'].mean()
avg_SALARY

np.float64(337.77777777777777)

In [49]:
e2.fillna({
    'SALARY':avg_SALARY})

,NAME,AGE,CITY,SALARY
1,Arun,26,Trichy,200.000000
2,Bharath,28,Bangalore,500.000000
3,Chetan,30,Mangalore,300.000000
4,Danu,28,Delhi,337.777778
5,Gani,23,Indore,400.000000
6,Hari,23,Jaipur,100.000000
7,Jay,24,Varanasi,400.000000
8,Hari,23,Jaipur,100.000000
9,Suresh,30,Hyderabad,800.000000
10,Vamshi,25,Kurnool,240.000000


In [50]:
#E-Remove any duplicate rows
e2.duplicated()

1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
dtype: bool

In [51]:
e2.drop_duplicates(
    #inplace=True
)

,NAME,AGE,CITY,SALARY
1,Arun,26,Trichy,200.0
2,Bharath,28,Bangalore,500.0
3,Chetan,30,Mangalore,300.0
4,Danu,28,Delhi,NaN
5,Gani,23,Indore,400.0
6,Hari,23,Jaipur,100.0
7,Jay,24,Varanasi,400.0
9,Suresh,30,Hyderabad,800.0
10,Vamshi,25,Kurnool,240.0
